spring:
  data:
    mongodb:
      host: localhost
      database: customer
      username: codewithtee
      password: password
      port: 6543
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.codewithtee.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.codewithtee.ecommerce.kafka.payment.PaymentConfirmation
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 6546
    username: codewithtee
    password: codewithtee
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
